on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Code Coverage
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Unit test
        run: |
            npm install -g yarn
            yarn install
            yarn test

      - name : Scan Code
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml # optional
          flags: unit_tests # optional
